// Structured placeholder control library for CMMC Level 1 (FAR 52.204-21 / NIST
// 800-171 aligned 17 practices). Plain-English summaries are placeholders that
// Pac-Sec Admins can refine in the Control Library editor. This is NOT the full
// official control text — it's a maintainable starting structure.
export const CONTROL_LIBRARY_SEED = [
  { framework: 'CMMC', cmmc_level: 'Level 1', domain: 'Access Control', control_id: 'AC.L1-3.1.1', control_title: 'Authorized Access Control', plain_english_summary: 'Only let approved users, processes, and devices onto your systems.', sort_order: 1 },
  { framework: 'CMMC', cmmc_level: 'Level 1', domain: 'Access Control', control_id: 'AC.L1-3.1.2', control_title: 'Transaction & Function Control', plain_english_summary: 'Limit what each user is allowed to do to only the tasks their role requires.', sort_order: 2 },
  { framework: 'CMMC', cmmc_level: 'Level 1', domain: 'Access Control', control_id: 'AC.L1-3.1.20', control_title: 'External Connections', plain_english_summary: 'Verify and control connections to and use of external systems.', sort_order: 3 },
  { framework: 'CMMC', cmmc_level: 'Level 1', domain: 'Access Control', control_id: 'AC.L1-3.1.22', control_title: 'Control Public Information', plain_english_summary: 'Control information that gets posted or processed on publicly accessible systems.', sort_order: 4 },
  { framework: 'CMMC', cmmc_level: 'Level 1', domain: 'Identification & Authentication', control_id: 'IA.L1-3.5.1', control_title: 'Identification', plain_english_summary: 'Give every user, process, and device a unique identity before granting access.', sort_order: 5 },
  { framework: 'CMMC', cmmc_level: 'Level 1', domain: 'Identification & Authentication', control_id: 'IA.L1-3.5.2', control_title: 'Authentication', plain_english_summary: 'Verify the identity of users and devices before allowing access (e.g. passwords, MFA).', sort_order: 6 },
  { framework: 'CMMC', cmmc_level: 'Level 1', domain: 'Media Protection', control_id: 'MP.L1-3.8.3', control_title: 'Media Disposal', plain_english_summary: 'Sanitize or destroy media containing FCI before disposal or reuse.', sort_order: 7 },
  { framework: 'CMMC', cmmc_level: 'Level 1', domain: 'Physical Protection', control_id: 'PE.L1-3.10.1', control_title: 'Limit Physical Access', plain_english_summary: 'Limit physical access to systems, equipment, and operating environments to authorized people.', sort_order: 8 },
  { framework: 'CMMC', cmmc_level: 'Level 1', domain: 'Physical Protection', control_id: 'PE.L1-3.10.3', control_title: 'Escort Visitors', plain_english_summary: 'Escort visitors and monitor their activity.', sort_order: 9 },
  { framework: 'CMMC', cmmc_level: 'Level 1', domain: 'Physical Protection', control_id: 'PE.L1-3.10.4', control_title: 'Physical Access Logs', plain_english_summary: 'Maintain audit logs of physical access.', sort_order: 10 },
  { framework: 'CMMC', cmmc_level: 'Level 1', domain: 'Physical Protection', control_id: 'PE.L1-3.10.5', control_title: 'Manage Physical Access', plain_english_summary: 'Control and manage physical access devices such as keys, badges, and locks.', sort_order: 11 },
  { framework: 'CMMC', cmmc_level: 'Level 1', domain: 'System & Communications Protection', control_id: 'SC.L1-3.13.1', control_title: 'Boundary Protection', plain_english_summary: 'Monitor and control communications at the external boundary and key internal boundaries.', sort_order: 12 },
  { framework: 'CMMC', cmmc_level: 'Level 1', domain: 'System & Communications Protection', control_id: 'SC.L1-3.13.5', control_title: 'Public-Access System Separation', plain_english_summary: 'Separate publicly accessible systems from internal networks.', sort_order: 13 },
  { framework: 'CMMC', cmmc_level: 'Level 1', domain: 'System & Information Integrity', control_id: 'SI.L1-3.14.1', control_title: 'Flaw Remediation', plain_english_summary: 'Identify, report, and fix system flaws (patching) in a timely way.', sort_order: 14 },
  { framework: 'CMMC', cmmc_level: 'Level 1', domain: 'System & Information Integrity', control_id: 'SI.L1-3.14.2', control_title: 'Malicious Code Protection', plain_english_summary: 'Provide protection from malicious code at appropriate locations.', sort_order: 15 },
  { framework: 'CMMC', cmmc_level: 'Level 1', domain: 'System & Information Integrity', control_id: 'SI.L1-3.14.4', control_title: 'Update Malicious Code Protection', plain_english_summary: 'Keep malicious code protection mechanisms up to date.', sort_order: 16 },
  { framework: 'CMMC', cmmc_level: 'Level 1', domain: 'System & Information Integrity', control_id: 'SI.L1-3.14.5', control_title: 'System & File Scanning', plain_english_summary: 'Perform periodic and real-time scans of the system and files from external sources.', sort_order: 17 },
];