export const prerequisites = [
  { key: 'sam_active', label: 'SAM.gov entity registration is active' },
  { key: 'uei_available', label: 'UEI is available' },
  { key: 'cage_active', label: 'CAGE code is active' },
  { key: 'eb_poc', label: 'EB POC is established in SAM' },
  { key: 'cage_hierarchy', label: 'CAGE hierarchy is correct' },
  { key: 'cam_assigned', label: 'Contractor Account Administrator (CAM) is assigned' },
  { key: 'ssp_exists', label: 'System Security Plan (SSP) exists' },
  { key: 'scope_identified', label: 'Assessment scope is identified' },
  { key: 'ao_identified', label: 'Affirming Official (AO) is identified' },
  { key: 'piee_account', label: 'PIEE user account exists or will be created' },
  { key: 'sprs_role', label: 'SPRS Cyber Vendor User role is requested or approved' },
];

export const stepSections = [
  {
    key: 'A',
    title: 'Get PIEE / SPRS Access',
    description: 'Confirm prerequisites and set up your PIEE account.',
    steps: [
      'Confirm SAM.gov entity registration is active.',
      'Confirm UEI is available.',
      'Confirm CAGE code is active.',
      'Confirm EB POC is established in SAM.',
      'Confirm CAGE hierarchy is correct in SAM.',
      'Confirm a Contractor Account Administrator (CAM) is assigned for your CAGE.',
      'Go to PIEE at https://piee.eb.mil/.',
      'If you already have a PIEE account, proceed to Section B.',
      'If you are a new user, proceed to Section C.',
    ],
  },
  {
    key: 'B',
    title: 'Existing PIEE User: Add SPRS Cyber Vendor User Role',
    description: 'Add the SPRS Cyber Vendor User role to your existing PIEE account.',
    steps: [
      'Log in to PIEE at https://piee.eb.mil/.',
      'Click My Account.',
      'Click Add Additional Roles.',
      'Verify your user profile and supervisor/agency information.',
      'Select SPRS (Supplier Performance Risk System) from the application list.',
      'Select SPRS Cyber Vendor User.',
      'Click Add Roles.',
      'Enter the Location Code / CAGE.',
      'Complete the justification, summary, and agreement steps.',
      'Wait for CAM approval. Check status via My Account > Manage Roles.',
    ],
  },
  {
    key: 'C',
    title: 'New PIEE User: Register and Request SPRS Role',
    description: 'Register a new PIEE account and request the SPRS Cyber Vendor User role.',
    steps: [
      'Go to PIEE at https://piee.eb.mil/.',
      'Click New User.',
      'Open New Vendor Organization / Getting Started Help.',
      'Review and complete the preliminary setup steps.',
      'Click Register.',
      'Read the privacy statement and click Agree.',
      'Select user type: Vendor.',
      'Select an authentication method.',
      'Complete the user profile and supervisor/agency information.',
      'Select SPRS (Supplier Performance Risk System) from the application list.',
      'Select SPRS Cyber Vendor User.',
      'Click Add Roles.',
      'Enter the Location Code / CAGE.',
      'Complete the justification, summary, and agreement steps.',
      'Wait for CAM activation. PIEE access is granted at registration, but SPRS access requires CAM activation.',
    ],
  },
  {
    key: 'D',
    title: 'Access SPRS Cyber Reports',
    description: 'Open SPRS and access the Cyber Reports module.',
    steps: [
      'Log in to PIEE at https://piee.eb.mil/.',
      'Select the SPRS tile.',
      'Select Cyber Reports or Cyber Reports, CMMC & NIST.',
      'Select the desired company hierarchy from the drop-down, identified by the HLO.',
      'Click Run Cyber Reports.',
      'Confirm the hierarchy has an asterisk (*) — this indicates you have the SPRS Cyber Vendor User role with add, edit, and delete access.',
    ],
  },
  {
    key: 'E',
    title: 'Enter CMMC Level 1 Self-Assessment',
    description: 'Enter a CMMC Level 1 self-assessment in SPRS Cyber Reports.',
    steps: [
      'Open Cyber Reports in SPRS.',
      'Select the desired company hierarchy.',
      'Open the CMMC Assessments tab.',
      'Select Add New Level 1 CMMC Self-Assessment.',
      'Enter assessment details.',
      'Enter the assessment date.',
      'Select assessment scope (e.g., enterprise or enclave).',
      'Enter employee count.',
      'Enter included CAGEs.',
      'Confirm FAR 52.204-21 compliance.',
      'Click Continue to Affirmation.',
      "If you are not the AO, enter the AO's email and select Transfer to AO.",
      'The AO reviews the assessment, certifies review of the affirmation statement, and selects Affirm.',
      'Note: A Final Level 1 Self-Assessment automatically expires after one year.',
    ],
  },
  {
    key: 'F',
    title: 'Enter CMMC Level 2 Self-Assessment',
    description: 'Enter a CMMC Level 2 self-assessment in SPRS Cyber Reports.',
    steps: [
      'Open Cyber Reports, CMMC & NIST in SPRS.',
      'Select the desired hierarchy.',
      'Click Run Cyber Reports.',
      'Open CMMC Assessments.',
      'Open the CMMC Level 2, Self tab.',
      'Select Add New Level 2 CMMC Self-Assessment.',
      'Enter assessment data.',
      'Review requirement objectives for each requirement number.',
      'Select the applicable compliance status for each requirement.',
      'Click Save and Continue through each requirement family.',
      'Review assessment details and make sure all requirements are complete.',
      'Add assessing scope.',
      'Add employee count.',
      'Add included CAGEs using Open CAGE Hierarchy or comma-delimited CAGE entries.',
      'Review the calculated score.',
      "If you are not the AO, enter the AO's email and select Transfer to AO.",
      'The AO reviews the assessment, certifies review of the affirmation statement, and selects Affirm.',
      'Note: Only Conditional Level 2 Self-Assessments (scores 88–109) and Final Level 2 Self-Assessments (score 110) can be affirmed.',
      'Note: Level 2 Conditional Self-Assessments are valid for 180 days; Final Level 2 Self-Assessments with annual affirmations are valid for 3 years.',
    ],
  },
  {
    key: 'G',
    title: 'Transfer to Affirming Official',
    description: 'Transfer the assessment to the Affirming Official (AO) for affirmation.',
    steps: [
      "After entering the assessment, if you are not the AO, enter the AO's email address.",
      'Select Transfer to AO.',
      'The AO will receive access to the assessment marked as Pending Affirmation.',
      'Confirm the AO has PIEE access and the SPRS Cyber Vendor User role.',
      'Notify the AO to log in and complete the affirmation (see Section H).',
    ],
  },
  {
    key: 'H',
    title: 'Affirm the Assessment',
    description: 'The Affirming Official reviews and affirms the assessment.',
    steps: [
      'AO logs in to PIEE at https://piee.eb.mil/.',
      'AO opens SPRS.',
      'AO opens Cyber Reports.',
      'AO opens the assessment marked Pending Affirmation.',
      'AO verifies personal information and authority to affirm.',
      'AO adds optional POCs if needed.',
      'AO reviews assessment results.',
      'AO certifies review of the affirmation statement.',
      'AO selects Affirm.',
      'Save the CMMC UID, final or conditional status, expiration date, and screenshots.',
    ],
  },
  {
    key: 'I',
    title: 'After Submission: Save Evidence and Monitor Expiration',
    description: 'Record all evidence and track the expiration date.',
    steps: [
      'Save the PIEE role approval screenshot.',
      'Save the SPRS Cyber Reports access screenshot.',
      'Save the selected CAGE hierarchy screenshot.',
      'Save the Level 1 or Level 2 assessment entry screenshot.',
      'Save the AO transfer screenshot (if applicable).',
      'Save the AO affirmation confirmation screenshot.',
      'Record the CMMC UID.',
      'Record the CMMC status (Final or Conditional).',
      'Record the expiration date.',
      'Record the date submitted and affirmed.',
      'Record the AO name and email.',
      'Monitor the expiration date — Level 1 expires in 1 year; Level 2 Conditional in 180 days; Level 2 Final in 3 years (with annual affirmations).',
    ],
  },
];

export const officialResources = [
  { name: 'DoD CIO CMMC Resources and Documentation', url: 'https://dodcio.defense.gov/CMMC/Resources-Documentation/', purpose: 'CMMC official documentation hub' },
  { name: 'SPRS Homepage', url: 'https://www.sprs.csd.disa.mil/', purpose: 'SPRS access, references, FAQs, training, and CMMC tutorials' },
  { name: 'SPRS Access Instructions', url: 'https://www.sprs.csd.disa.mil/access.htm', purpose: 'Vendor PIEE/SPRS role instructions' },
  { name: 'SPRS Vendor Cyber Reports Access Guide', url: 'https://www.sprs.csd.disa.mil/pdf/SPRS_Access_CyberReports.pdf', purpose: 'Existing and new PIEE user role request steps' },
  { name: 'CMMC Level 1 Quick Entry Guide', url: 'https://www.sprs.csd.disa.mil/pdf/CMMCQuickEntryGuide.pdf', purpose: 'Level 1 self-assessment entry and affirmation' },
  { name: 'CMMC Level 2 Self-Assessment Quick Entry Guide', url: 'https://www.sprs.csd.disa.mil/pdf/CMMCL2SelfQuickEntryGuide.pdf', purpose: 'Level 2 self-assessment entry, scoring, and affirmation' },
  { name: 'Affirming Official Tutorial', url: 'https://www.sprs.csd.disa.mil/pdf/training/AffirmingOfficialTutorialforCMMC-Presentation.pdf', purpose: 'AO definition and affirmation process' },
];

export const evidenceItems = [
  { key: 'piee_role_screenshot', label: 'PIEE role approval screenshot' },
  { key: 'sprs_cyber_screenshot', label: 'SPRS Cyber Reports screenshot' },
  { key: 'assessment_screenshot', label: 'Assessment details screenshot' },
  { key: 'ao_affirmation_screenshot', label: 'AO affirmation confirmation screenshot' },
  { key: 'cmmc_status', label: 'Final CMMC status' },
  { key: 'cmmc_uid', label: 'CMMC UID' },
  { key: 'expiration_date', label: 'Expiration date' },
  { key: 'date_submitted', label: 'Date submitted' },
  { key: 'entered_by', label: 'Name of person who entered assessment' },
  { key: 'ao_name', label: 'Name of AO who affirmed' },
];