import { useState } from 'react';
import { X, Copy, Check, FileText } from 'lucide-react';

function fmtDate(d) {
  if (!d) return 'N/A';
  const date = new Date(d);
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

export default function WeeklyReportModal({ client, l1Controls, l2Controls, tasks, onClose }) {
  const [copied, setCopied] = useState(false);

  const today = new Date();
  const weekAgo = new Date(today);
  weekAgo.setDate(weekAgo.getDate() - 7);
  const todayStr = today.toISOString().split('T')[0];
  const weekAgoStr = weekAgo.toISOString().split('T')[0];

  const l1Complete = l1Controls.filter(c => c.status === 'Complete' || c.ready_for_assessment).length;
  const l2Complete = l2Controls.filter(c => c.status === 'Complete' || c.ready_for_assessment).length;
  const tasksComplete = tasks.filter(t => t.status === 'Complete').length;
  const overallPct = tasks.length ? Math.round((tasksComplete / tasks.length) * 100) : 0;
  const l1Pct = l1Controls.length ? Math.round((l1Complete / l1Controls.length) * 100) : 0;
  const l2Pct = l2Controls.length ? Math.round((l2Complete / l2Controls.length) * 100) : 0;

  const completedThisWeek = tasks.filter(t =>
    t.status === 'Complete' && t.updated_date && t.updated_date >= weekAgoStr
  );
  const inProgress = tasks.filter(t => t.status === 'In Progress');
  const blockers = tasks.filter(t => t.status === 'Blocker' || t.priority === 'Critical');
  const upcoming = tasks
    .filter(t => t.status === 'Not Started' && t.due_date && t.due_date >= todayStr)
    .sort((a, b) => new Date(a.due_date) - new Date(b.due_date))
    .slice(0, 5);
  const currentPhase = tasks.find(t => t.status === 'In Progress')?.phase || 'Not Started';

  const report = [
    'CMMC COMMAND CENTER — WEEKLY STATUS REPORT',
    '',
    `Client: ${client.legal_name}`,
    `Report Date: ${fmtDate(todayStr)}`,
    `Reporting Period: ${fmtDate(weekAgoStr)} – ${fmtDate(todayStr)}`,
    '',
    '═══════════════════════════════════════════════',
    '',
    'PROJECT SUMMARY',
    `Project Status: ${client.project_status || 'Not Started'}`,
    `Current Phase: ${currentPhase}`,
    `Overall Task Completion: ${tasksComplete}/${tasks.length} (${overallPct}%)`,
    '',
    'LEVEL 1 PROGRESS',
    `Controls Complete: ${l1Complete}/${l1Controls.length} (${l1Pct}%)`,
    '',
    'LEVEL 2 READINESS',
    `Controls Complete: ${l2Complete}/${l2Controls.length} (${l2Pct}%)`,
    '',
    '═══════════════════════════════════════════════',
    '',
    'COMPLETED THIS WEEK',
    completedThisWeek.length > 0
      ? completedThisWeek.map(t => `  ✓ ${t.title}`).join('\n')
      : '  No tasks completed this week.',
    '',
    'IN PROGRESS',
    inProgress.length > 0
      ? inProgress.map(t => `  → ${t.title}${t.phase ? ` (${t.phase})` : ''}`).join('\n')
      : '  No tasks currently in progress.',
    '',
    'BLOCKERS & CRITICAL ITEMS',
    blockers.length > 0
      ? blockers.map(t => `  ⚠ ${t.title}${t.priority === 'Critical' ? ' [Critical]' : ''}`).join('\n')
      : '  No blockers or critical items.',
    '',
    'UPCOMING TASKS',
    upcoming.length > 0
      ? upcoming.map(t => `  • ${t.title} (Due: ${fmtDate(t.due_date)})`).join('\n')
      : '  No upcoming tasks with due dates.',
    '',
    '═══════════════════════════════════════════════',
    '',
    'WEEKLY SUMMARY',
    buildNarrative(client, completedThisWeek.length, inProgress.length, blockers.length, overallPct, l1Pct, currentPhase),
    '',
    'Generated by CMMC Command Center',
  ].join('\n');

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(report);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (e) {
      // fallback - select the textarea
    }
  };

  return (
    <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4" onClick={onClose}>
      <div className="bg-white rounded-2xl max-w-2xl w-full max-h-[90vh] flex flex-col" onClick={e => e.stopPropagation()}>
        <div className="flex items-center justify-between p-5 border-b border-slate-200">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-[#0F1E3C]" />
            <h2 className="text-lg font-bold text-slate-900">Weekly Client Report</h2>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-600"><X className="w-5 h-5" /></button>
        </div>

        <div className="p-5 flex-1 overflow-y-auto">
          <p className="text-xs text-slate-500 mb-3">
            Generated for <span className="font-semibold text-slate-700">{client.legal_name}</span> — covers the past 7 days. Copy and paste into an email to your client.
          </p>
          <textarea
            readOnly
            value={report}
            className="w-full h-[400px] text-xs font-mono text-slate-700 bg-slate-50 border border-slate-200 rounded-lg p-4 resize-none focus:outline-none focus:ring-2 focus:ring-blue-500/30"
          />
        </div>

        <div className="flex justify-end gap-2 p-5 border-t border-slate-200">
          <button onClick={onClose} className="px-4 py-2 text-sm text-slate-600 hover:bg-slate-100 rounded-lg">Close</button>
          <button
            onClick={handleCopy}
            className="flex items-center gap-2 px-4 py-2 text-sm bg-[#0F1E3C] text-white rounded-lg hover:bg-[#1E2D4A]"
          >
            {copied ? <><Check className="w-4 h-4" /> Copied!</> : <><Copy className="w-4 h-4" /> Copy Report</>}
          </button>
        </div>
      </div>
    </div>
  );
}

function buildNarrative(client, completedCount, inProgressCount, blockerCount, overallPct, l1Pct, currentPhase) {
  let parts = [];
  if (completedCount > 0) {
    parts.push(`This week we completed ${completedCount} task${completedCount !== 1 ? 's' : ''} and overall project completion is at ${overallPct}%.`);
  } else {
    parts.push(`Overall project completion is at ${overallPct}%.`);
  }
  if (inProgressCount > 0) {
    parts.push(`We currently have ${inProgressCount} item${inProgressCount !== 1 ? 's' : ''} in progress, with the current focus on ${currentPhase}.`);
  }
  parts.push(`Level 1 control completion is at ${l1Pct}%.`);
  if (blockerCount > 0) {
    parts.push(`There ${blockerCount !== 1 ? 'are' : 'is'} ${blockerCount} blocker${blockerCount !== 1 ? 's' : ''} requiring attention.`);
  } else {
    parts.push('No blockers are currently impacting the project timeline.');
  }
  return parts.join(' ');
}