// Palo Alto Cortex XDR CMMC Technician Runbook content. Static guidance only — no API calls.

export const CORTEX_RUNBOOK = {
  tool_name: 'Palo Alto Cortex XDR',
  title: 'Palo Alto Cortex XDR CMMC Technician Runbook',
  subtitle: 'Step-by-step endpoint protection setup, evidence collection, and control mapping guide.',
  intro:
    'This runbook guides technicians through preparing Palo Alto Cortex XDR to support CMMC Level 2 readiness. Cortex XDR may provide supporting evidence for selected controls related to endpoint protection, malware prevention, exploit protection, alert monitoring, incident investigation, response capability, and administrative access. Cortex XDR does not satisfy CMMC requirements by itself. All evidence must be validated by authorized personnel.',
  evidenceNaming: {
    format: 'CONTROLID_ToolName_EvidenceDescription_YYYY-MM-DD.png',
    toolName: 'CortexXDR',
    examples: [
      'SI.L2-3.14.2_CortexXDR_Malware_Prevention_Policy_2026-07-05.png',
      'SI.L2-3.14.6_CortexXDR_Alert_Dashboard_2026-07-05.png',
      'IR.L2-3.6.1_CortexXDR_Incident_Workflow_2026-07-05.png',
      'AC.L2-3.1.2_CortexXDR_Admin_User_List_2026-07-05.png',
      'SI.L2-3.14.7_CortexXDR_Endpoint_Isolation_Capability_2026-07-05.png',
    ],
    rules: [
      'Start every file name with the primary CMMC control ID.',
      'Use CortexXDR as the tool name.',
      'Use short descriptive names.',
      'Use underscores instead of spaces.',
      'Use YYYY-MM-DD date format.',
      'Do not use vague names like screenshot1.png, evidence.png, or cortex.png.',
      'If one screenshot supports multiple controls, name it after the primary control and map it to additional controls inside Kipuka.',
      'Sanitize sensitive alert or incident data before upload when necessary.',
    ],
  },
  mappingGroups: [
    { label: 'Endpoint coverage evidence may support', controls: ['SI.L2-3.14.2', 'SI.L2-3.14.3', 'SI.L2-3.14.4', 'CM.L2-3.4.1', 'CA.L2-3.12.3'] },
    { label: 'Malware and exploit prevention evidence may support', controls: ['SI.L2-3.14.2', 'SI.L2-3.14.3', 'SI.L2-3.14.4', 'SI.L2-3.14.5', 'SI.L2-3.14.6', 'SI.L2-3.14.7'] },
    { label: 'Alert and monitoring evidence may support', controls: ['SI.L2-3.14.6', 'SI.L2-3.14.7', 'AU.L2-3.3.1', 'AU.L2-3.3.3', 'IR.L2-3.6.1', 'IR.L2-3.6.2'] },
    { label: 'Incident workflow evidence may support', controls: ['IR.L2-3.6.1', 'IR.L2-3.6.2', 'IR.L2-3.6.3', 'SI.L2-3.14.6', 'SI.L2-3.14.7'] },
    { label: 'Admin access evidence may support', controls: ['AC.L2-3.1.1', 'AC.L2-3.1.2', 'AC.L2-3.1.5', 'AC.L2-3.1.6', 'IA.L2-3.5.3', 'IA.L2-3.5.5'] },
  ],
  finalWarning:
    'Do not mark controls as implemented based only on Cortex XDR evidence. Cortex XDR evidence is supporting evidence. Final control status must consider policy, process, configuration, interviews, implementation, and reviewer validation.',
  sections: [
    {
      key: 'overview',
      title: 'Technician Checklist Overview',
      purpose: 'Track overall progress through the Cortex XDR readiness workflow at a glance.',
      checklist: [
        'Cortex XDR tenant verified',
        'Client scope confirmed',
        'In-scope endpoints reporting',
        'Out-of-scope endpoints documented',
        'Endpoint groups configured',
        'Agent policy reviewed',
        'Malware prevention reviewed',
        'Exploit prevention reviewed',
        'Alert dashboard reviewed',
        'Incident workflow reviewed',
        'Response capabilities reviewed if licensed/configured',
        'Admin access reviewed',
        'Evidence screenshots captured',
        'Reports exported',
        'Evidence files named correctly',
        'Evidence uploaded',
        'Evidence mapped to controls',
        'Gaps converted to POA&M or ACOLYTE remediation items',
        'Technician review complete',
      ],
    },
    {
      key: 'tenant_scope',
      title: 'Verify Cortex XDR Tenant and Project Scope',
      purpose: 'Confirm the correct tenant and that endpoint scope matches the CMMC boundary.',
      steps: [
        'Log in to Palo Alto Cortex XDR using an authorized administrator account.',
        'Confirm the correct tenant/customer is selected.',
        'Confirm the client organization matches the Kipuka project.',
        'Confirm the endpoint scope matches the CMMC boundary.',
        'Confirm license level and available capabilities.',
        'Document any endpoint groups or systems that are out of scope.',
        'Capture tenant and scope evidence.',
      ],
      evidenceFiles: [
        'SI.L2-3.14.2_CortexXDR_Tenant_Overview_YYYY-MM-DD.png',
        'CM.L2-3.4.1_CortexXDR_Endpoint_Scope_YYYY-MM-DD.png',
        'CA.L2-3.12.1_CortexXDR_CMMC_Scope_Endpoint_List_YYYY-MM-DD.png',
      ],
      controls: ['SI.L2-3.14.2', 'SI.L2-3.14.3', 'CM.L2-3.4.1', 'CA.L2-3.12.1', 'CA.L2-3.12.3'],
    },
    {
      key: 'coverage',
      title: 'Configure Endpoint Groups and Agent Coverage',
      purpose: 'Ensure every in-scope endpoint has an active agent reporting recently.',
      steps: [
        'Review all endpoints reporting to Cortex XDR.',
        'Confirm every in-scope endpoint has an active Cortex XDR agent.',
        'Confirm each endpoint shows recent check-in/heartbeat.',
        'Create or verify endpoint groups that align to the CMMC boundary.',
        'Identify stale, retired, duplicate, or out-of-scope endpoints.',
        'Capture endpoint coverage dashboard and group evidence.',
      ],
      evidenceFiles: [
        'SI.L2-3.14.2_CortexXDR_Endpoint_Coverage_Dashboard_YYYY-MM-DD.png',
        'SI.L2-3.14.2_CortexXDR_Agent_CheckIn_Status_YYYY-MM-DD.png',
        'CM.L2-3.4.1_CortexXDR_Endpoint_Groups_YYYY-MM-DD.png',
        'CA.L2-3.12.3_CortexXDR_InScope_Endpoint_Coverage_YYYY-MM-DD.png',
      ],
      controls: ['SI.L2-3.14.2', 'SI.L2-3.14.3', 'SI.L2-3.14.4', 'CM.L2-3.4.1', 'CA.L2-3.12.3'],
    },
    {
      key: 'agent_policies',
      title: 'Configure Agent Policies',
      purpose: 'Confirm in-scope endpoint groups receive the intended agent policy.',
      steps: [
        'Review assigned agent policies for in-scope endpoints.',
        'Confirm endpoint groups receive the intended policy.',
        'Confirm policy names are clear and client-specific.',
        'Document any policy exceptions.',
        'Capture agent policy and assignment evidence.',
      ],
      evidenceFiles: [
        'CM.L2-3.4.2_CortexXDR_Agent_Policy_YYYY-MM-DD.png',
        'CM.L2-3.4.6_CortexXDR_Policy_Assignments_YYYY-MM-DD.png',
        'CM.L2-3.4.7_CortexXDR_Policy_Enforcement_YYYY-MM-DD.png',
      ],
      controls: ['CM.L2-3.4.2', 'CM.L2-3.4.6', 'CM.L2-3.4.7', 'SI.L2-3.14.2', 'SI.L2-3.14.4'],
    },
    {
      key: 'prevention',
      title: 'Configure Malware and Exploit Prevention',
      purpose: 'Confirm malware, exploit, and threat protection are applied to in-scope endpoints.',
      steps: [
        'Review malware prevention settings.',
        'Review exploit prevention settings.',
        'Review behavioral threat protection settings if available.',
        'Review device control or host firewall features only if configured and licensed.',
        'Confirm in-scope endpoints receive prevention policies.',
        'Capture policy screenshots.',
      ],
      evidenceFiles: [
        'SI.L2-3.14.2_CortexXDR_Malware_Prevention_Policy_YYYY-MM-DD.png',
        'SI.L2-3.14.2_CortexXDR_Exploit_Prevention_Policy_YYYY-MM-DD.png',
        'SI.L2-3.14.4_CortexXDR_Threat_Protection_Settings_YYYY-MM-DD.png',
        'SI.L2-3.14.5_CortexXDR_Malware_Protection_Update_Status_YYYY-MM-DD.png',
      ],
      controls: ['SI.L2-3.14.2', 'SI.L2-3.14.3', 'SI.L2-3.14.4', 'SI.L2-3.14.5', 'SI.L2-3.14.6', 'SI.L2-3.14.7'],
    },
    {
      key: 'alerting',
      title: 'Configure Alerting and Monitoring',
      purpose: 'Confirm alerts are visible, triaged, and escalated appropriately.',
      steps: [
        'Review the Cortex XDR alert dashboard.',
        'Confirm alert severity categories are visible.',
        'Confirm who reviews alerts.',
        'Confirm escalation path.',
        'Confirm alert triage process.',
        'Capture alert dashboard, alert severity, and alert workflow evidence.',
      ],
      evidenceFiles: [
        'SI.L2-3.14.6_CortexXDR_Alert_Dashboard_YYYY-MM-DD.png',
        'SI.L2-3.14.7_CortexXDR_Security_Alerts_YYYY-MM-DD.png',
        'IR.L2-3.6.1_CortexXDR_Alert_Triage_Process_YYYY-MM-DD.png',
        'IR.L2-3.6.2_CortexXDR_Alert_Escalation_Workflow_YYYY-MM-DD.png',
      ],
      controls: ['SI.L2-3.14.6', 'SI.L2-3.14.7', 'AU.L2-3.3.1', 'AU.L2-3.3.3', 'IR.L2-3.6.1', 'IR.L2-3.6.2'],
    },
    {
      key: 'incident',
      title: 'Configure Incident Investigation and Response Workflow',
      purpose: 'Confirm the investigation and response workflow and capabilities.',
      steps: [
        'Review incident/case workflow.',
        'Confirm investigation process.',
        'Confirm response actions available to authorized admins.',
        'Confirm isolation/quarantine capability if configured.',
        'Confirm evidence handling expectations.',
        'Capture incident/case workflow and response capability screenshots.',
      ],
      evidenceFiles: [
        'IR.L2-3.6.1_CortexXDR_Incident_Workflow_YYYY-MM-DD.png',
        'IR.L2-3.6.2_CortexXDR_Incident_Response_Actions_YYYY-MM-DD.png',
        'IR.L2-3.6.3_CortexXDR_Incident_Review_Evidence_YYYY-MM-DD.png',
        'SI.L2-3.14.7_CortexXDR_Endpoint_Isolation_Capability_YYYY-MM-DD.png',
      ],
      controls: ['IR.L2-3.6.1', 'IR.L2-3.6.2', 'IR.L2-3.6.3', 'SI.L2-3.14.6', 'SI.L2-3.14.7'],
    },
    {
      key: 'admin_access',
      title: 'Review Administrative Access and Roles',
      purpose: 'Confirm least-privilege admin access to Cortex XDR.',
      steps: [
        'Review Cortex XDR admin users.',
        'Confirm role-based access.',
        'Confirm privileged access is limited.',
        'Confirm MFA/SSO where available.',
        'Capture admin user and role evidence.',
      ],
      evidenceFiles: [
        'AC.L2-3.1.2_CortexXDR_Admin_User_List_YYYY-MM-DD.png',
        'AC.L2-3.1.5_CortexXDR_Role_Assignments_YYYY-MM-DD.png',
        'IA.L2-3.5.3_CortexXDR_Admin_MFA_Settings_YYYY-MM-DD.png',
        'IA.L2-3.5.5_CortexXDR_Admin_Identity_Review_YYYY-MM-DD.png',
      ],
      controls: ['AC.L2-3.1.1', 'AC.L2-3.1.2', 'AC.L2-3.1.5', 'AC.L2-3.1.6', 'IA.L2-3.5.3', 'IA.L2-3.5.5'],
    },
    {
      key: 'gather_evidence',
      title: 'Gather Evidence Screenshots and Reports',
      purpose: 'Assemble the full Cortex XDR evidence package.',
      evidenceTable: [
        'Tenant overview',
        'Endpoint coverage dashboard',
        'Endpoint group/scope screenshot',
        'Agent check-in status',
        'Agent policy screenshot',
        'Malware prevention policy screenshot',
        'Exploit prevention policy screenshot',
        'Alert dashboard screenshot',
        'Security alerts screenshot',
        'Incident/case workflow screenshot',
        'Response capability screenshot, if configured',
        'Endpoint isolation capability, if configured',
        'Admin user list',
        'Admin role assignments',
        'MFA/SSO settings, if available',
        'Sanitized detection/prevention event sample, if available',
        'Monthly endpoint protection summary, if available',
      ],
    },
    {
      key: 'naming',
      title: 'Evidence Naming Standard',
      purpose: 'Name every file consistently so evidence maps cleanly to controls.',
      isNaming: true,
    },
    {
      key: 'upload',
      title: 'Upload Evidence to Kipuka',
      purpose: 'Log each named artifact in the Evidence Vault and map it to controls.',
      isUpload: true,
      steps: [
        'Open the client project in Kipuka.',
        'Go to Evidence Vault.',
        'Click Upload Evidence.',
        'Select source tool: Palo Alto Cortex XDR.',
        'Upload the properly named screenshot or report.',
        'Set evidence type: Screenshot, Report Export, Configuration Export, Dashboard View, Log, or Other.',
        'Enter evidence date.',
        'Add owner.',
        'Add description explaining what the evidence shows.',
        'Map the evidence to the applicable controls.',
        'Set review status to Needs Review.',
        'Save the evidence record.',
        'Verify it appears under the mapped controls.',
      ],
    },
    {
      key: 'mapping',
      title: 'Map Evidence to CMMC Controls',
      purpose: 'Map Cortex XDR evidence only to controls it actually supports.',
      isMapping: true,
      importantNote:
        'Cortex XDR evidence should be mapped only to controls it actually supports. Do not map Cortex XDR evidence to every CMMC control.',
    },
    {
      key: 'gaps',
      title: 'Create POA&M or ACOLYTE Remediation Items for Gaps',
      purpose: 'Convert unresolved gaps into tracked remediation work — manually.',
      isGaps: true,
      steps: [
        'Review missing evidence and failed configuration items.',
        'For each unresolved issue, decide whether it requires: POA&M item, ACOLYTE remediation item, Both, or Technician note only.',
        'Create a POA&M item for compliance-impacting gaps.',
        'Create an ACOLYTE remediation item for operational cyber readiness gaps if ACOLYTE is enabled.',
        'Link the gap to the related evidence and controls.',
      ],
      lists: [
        {
          label: 'Example gaps',
          items: [
            'In-scope endpoints missing Cortex XDR agent',
            'Malware prevention policy not documented',
            'Alert review process not documented',
            'Incident workflow not documented',
            'Admin MFA not confirmed',
            'High-severity alerts unresolved',
            'Endpoint isolation capability not validated',
          ],
        },
      ],
    },
    {
      key: 'final_review',
      title: 'Final Technician Review',
      purpose: 'Confirm the Cortex XDR evidence package is complete and reviewer-ready.',
      isFinal: true,
      checklist: [
        'Cortex XDR tenant is correct.',
        'Endpoint scope matches the CMMC project.',
        'In-scope endpoints are reporting.',
        'Out-of-scope endpoints are documented.',
        'Endpoint groups are configured.',
        'Agent policy evidence captured.',
        'Malware prevention evidence captured.',
        'Exploit prevention evidence captured.',
        'Alert dashboard evidence captured.',
        'Incident workflow evidence captured.',
        'Response capability evidence captured, if applicable.',
        'Admin access evidence captured.',
        'All screenshots are named using the required naming standard.',
        'Evidence is uploaded to Kipuka.',
        'Evidence is mapped only to applicable controls.',
        'Gaps are converted to POA&M or ACOLYTE remediation items.',
        'Technician notes are complete.',
        'Evidence review status is set to Needs Review.',
        'Pac-Sec or client reviewer is assigned.',
      ],
    },
  ],
};

export const RUNBOOKS = {};