// Microsoft Intune CMMC Technician Runbook content. Static guidance only.
// Covers device management via the Intune admin center (intune.microsoft.com)
// for CMMC Level 2 readiness: enrollment, compliance, configuration baselines,
// encryption, app control, and lost-device procedures.
// Enclave note: endpoints that access CUI (e.g., PreVeil clients) are CUI
// assets — Intune is a Security Protection Asset managing them, and its
// policies and evidence remain fully in scope.

export const INTUNE_RUNBOOK = {
  tool_name: 'Microsoft Intune',
  title: 'Microsoft Intune CMMC Technician Runbook',
  subtitle: 'Device management setup: enrollment, compliance policy, security baselines, encryption, app control, and lost-device procedures.',
  intro:
    'This runbook guides technicians through configuring Microsoft Intune to support CMMC Level 2 readiness. Intune enforces device compliance (encryption, OS version, protection active), configuration baselines (screen lock, firewall, removable media), and app control across in-scope endpoints and mobile devices. Intune does not satisfy CMMC requirements by itself — policies must be assigned to ALL in-scope devices, noncompliance must have consequences (Conditional Access), and all evidence requires reviewer validation.',
  evidenceNaming: {
    format: 'CONTROLID_ToolName_EvidenceDescription_YYYY-MM-DD.png',
    toolName: 'Intune',
    examples: [
      'CM.L2-3.4.2_Intune_Compliance_Policy_Settings_2026-07-10.png',
      'SC.L2-3.13.11_Intune_BitLocker_Policy_2026-07-10.png',
      'AC.L2-3.1.10_Intune_ScreenLock_Policy_2026-07-10.png',
      'MP.L2-3.8.7_Intune_Removable_Media_Policy_2026-07-10.png',
      'CM.L2-3.4.1_Intune_Enrolled_Device_List_2026-07-10.png',
    ],
    rules: [
      'Start every file name with the primary CMMC control ID.',
      'Use Intune as the tool name.',
      'Use short descriptive names with underscores instead of spaces.',
      'Use YYYY-MM-DD date format.',
      'Do not use vague names like screenshot1.png or intune.png.',
      'If one screenshot supports multiple controls, name it after the primary control and map it to additional controls on the current control's Evidence page.',
      'Sanitize user or device names your project rules mark as sensitive before upload.',
    ],
  },
  mappingGroups: [
    { label: 'Device inventory/enrollment evidence may support', controls: ['CM.L2-3.4.1', 'CM.L2-3.4.2', 'CA.L2-3.12.3', 'AC.L2-3.1.18'] },
    { label: 'Compliance policy evidence may support', controls: ['CM.L2-3.4.2', 'CM.L2-3.4.6', 'SI.L2-3.14.1', 'AC.L2-3.1.1'] },
    { label: 'Encryption evidence may support', controls: ['SC.L2-3.13.11', 'SC.L2-3.13.16', 'AC.L2-3.1.19', 'MP.L2-3.8.9'] },
    { label: 'Session/screen lock evidence may support', controls: ['AC.L2-3.1.10', 'AC.L2-3.1.11'] },
    { label: 'Removable media evidence may support', controls: ['MP.L2-3.8.7', 'MP.L2-3.8.8', 'MP.L2-3.8.1'] },
    { label: 'App control evidence may support', controls: ['CM.L2-3.4.8', 'CM.L2-3.4.9', 'AC.L2-3.1.18'] },
    { label: 'Lost/retired device evidence may support', controls: ['MP.L2-3.8.3', 'AC.L2-3.1.18', 'AC.L2-3.1.19'] },
  ],
  finalWarning:
    'Do not mark controls as implemented based only on Intune evidence. A policy that exists but is not assigned to every in-scope device group proves nothing, and noncompliant devices with no access consequence fail interviews. Policy, process, and reviewer validation are still required.',
  sections: [
    {
      key: 'overview',
      title: 'Technician Checklist Overview',
      purpose: 'Track overall progress through the Intune readiness workflow at a glance.',
      checklist: [
        'Admin roles reviewed; least-privilege access',
        'All in-scope devices enrolled; inventory matches asset list',
        'Enrollment restrictions and BYOD stance documented',
        'Compliance policy enforced (encryption, OS, protection) with consequences',
        'Security baseline / configuration profiles applied',
        'BitLocker/FileVault enforced with recovery keys escrowed',
        'Screen lock and session controls configured',
        'Removable media policy enforced',
        'App control approach documented and applied',
        'Lost-device wipe procedure documented and tested',
        'Evidence screenshots captured with correct names',
        'Evidence mapped to the required controls',
      ],
    },
    {
      key: 'access',
      title: 'Secure Admin Access and Roles',
      purpose: 'Control who can push device policy to the fleet.',
      steps: [
        'Sign in to the Intune admin center at intune.microsoft.com with an MFA-protected admin account.',
        'Review role assignments (Tenant administration > Roles): apply least privilege; remove stale Intune Administrators.',
        'Document the admin roster and review cadence.',
        'Capture evidence of role assignments.',
      ],
      evidenceFiles: [
        'AC.L2-3.1.5_Intune_Admin_Role_Assignments_YYYY-MM-DD.png',
      ],
      controls: ['AC.L2-3.1.5', 'AC.L2-3.1.6'],
    },
    {
      key: 'enrollment',
      title: 'Enroll All In-Scope Devices',
      purpose: 'Unmanaged in-scope devices are unprotected in-scope devices — enrollment coverage is the foundation.',
      steps: [
        'Open Devices > All devices; export or screenshot the enrolled list.',
        'Compare against Final Inventory & Scope: every in-scope Windows/macOS/iOS/Android device that touches company data must be enrolled (or documented out of scope with justification).',
        'Enroll missing devices (Windows: Entra join or Autopilot; mobile: Company Portal).',
        'Set enrollment restrictions: decide and document the BYOD stance — either block personal devices, or manage them with app protection policies; write the decision into the scoping notes.',
        'Document any device that cannot be enrolled and create a POA&M item for compensating protection.',
        'Capture evidence: enrolled device list, enrollment restrictions.',
      ],
      evidenceFiles: [
        'CM.L2-3.4.1_Intune_Enrolled_Device_List_YYYY-MM-DD.png',
        'AC.L2-3.1.18_Intune_Enrollment_Restrictions_YYYY-MM-DD.png',
      ],
      controls: ['CM.L2-3.4.1', 'CM.L2-3.4.2', 'AC.L2-3.1.18', 'CA.L2-3.12.3'],
    },
    {
      key: 'compliance',
      title: 'Enforce Device Compliance with Consequences',
      purpose: 'Compliance policy defines the minimum healthy device — and noncompliance must cost access.',
      steps: [
        'Create or verify the compliance policy (Devices > Compliance policies) per platform.',
        'Windows minimums: BitLocker required, Secure Boot required, minimum OS version set, Defender antivirus/antimalware active and current, real-time protection required.',
        'Mobile minimums: encryption required, PIN/passcode required, minimum OS, no jailbroken/rooted devices.',
        'Set actions for noncompliance: mark noncompliant immediately (or short grace, e.g. 3 days) — never an indefinite grace period.',
        'Verify the Entra Conditional Access policy that requires a COMPLIANT device for access to company resources is enforced (this is the consequence that makes compliance real).',
        'Review the compliance report; drive noncompliant devices to green or document exceptions.',
        'Capture evidence: policy settings, actions for noncompliance, compliance report, the CA policy requiring compliant devices.',
      ],
      evidenceFiles: [
        'CM.L2-3.4.2_Intune_Compliance_Policy_Settings_YYYY-MM-DD.png',
        'CM.L2-3.4.2_Intune_Compliance_Report_YYYY-MM-DD.png',
        'AC.L2-3.1.1_Intune_CA_Require_Compliant_Device_YYYY-MM-DD.png',
      ],
      controls: ['CM.L2-3.4.2', 'CM.L2-3.4.6', 'AC.L2-3.1.1', 'SI.L2-3.14.1'],
    },
    {
      key: 'baseline',
      title: 'Apply Configuration Baselines',
      purpose: 'A documented, enforced baseline is what CM.L2-3.4.1/3.4.2 actually ask for.',
      steps: [
        'Apply the Intune Security Baseline for Windows (Endpoint security > Security baselines) or an equivalent documented configuration profile set; record every deliberate deviation with justification.',
        'Enforce: host firewall ON (all profiles), SmartScreen enabled, password/lock policies per the org policy.',
        'Export or screenshot the baseline/profile settings — THIS is the approved baseline document assessors ask for; store it in the evidence vault.',
        'Assign baselines/profiles to ALL in-scope device groups; verify assignment status shows succeeded.',
        'Capture evidence: baseline summary, deviation log, assignment status.',
      ],
      evidenceFiles: [
        'CM.L2-3.4.1_Intune_Security_Baseline_Summary_YYYY-MM-DD.png',
        'CM.L2-3.4.1_Intune_Baseline_Assignment_Status_YYYY-MM-DD.png',
      ],
      controls: ['CM.L2-3.4.1', 'CM.L2-3.4.2', 'CM.L2-3.4.6', 'SC.L2-3.13.1'],
    },
    {
      key: 'encryption',
      title: 'Enforce Disk Encryption with Key Escrow',
      purpose: 'Every endpoint that can touch CUI must be encrypted, with recovery keys recoverable by the org — not the user.',
      steps: [
        'Create the disk encryption policy (Endpoint security > Disk encryption): BitLocker for Windows (require device encryption, block write to non-encrypted removable drives per MP policy), FileVault for macOS.',
        'Require BitLocker recovery keys to escrow to Entra ID; verify a sample device\u2019s key is visible in the device record.',
        'For FIPS claims: note that the SC.L2-3.13.11 FIPS-validated cryptography argument requires the CMVP certificate references for the crypto modules in use — record certificate numbers in the control notes, not just "BitLocker on".',
        'Enforce mobile device encryption via the compliance policy (previous section).',
        'Capture evidence: encryption policy, escrowed key example (redact the key value), encryption status report.',
      ],
      evidenceFiles: [
        'SC.L2-3.13.11_Intune_BitLocker_Policy_YYYY-MM-DD.png',
        'SC.L2-3.13.16_Intune_Encryption_Status_Report_YYYY-MM-DD.png',
      ],
      controls: ['SC.L2-3.13.11', 'SC.L2-3.13.16', 'AC.L2-3.1.19', 'MP.L2-3.8.9'],
    },
    {
      key: 'session',
      title: 'Screen Lock and Session Controls',
      purpose: 'Unattended, unlocked devices are the simplest CUI exposure there is.',
      steps: [
        'Enforce screen lock after inactivity (15 minutes or less per org policy) with password/PIN to resume, via configuration profile or baseline.',
        'Enforce lock-on-lid-close / display-off behavior on laptops.',
        'For shared or kiosk devices, document the session termination approach.',
        'Capture evidence: the lock policy settings and one device honoring them.',
      ],
      evidenceFiles: [
        'AC.L2-3.1.10_Intune_ScreenLock_Policy_YYYY-MM-DD.png',
      ],
      controls: ['AC.L2-3.1.10', 'AC.L2-3.1.11'],
    },
    {
      key: 'media',
      title: 'Control Removable Media',
      purpose: 'Removable media is the classic CUI leak path — enforce the written policy technically.',
      steps: [
        'Implement the org\u2019s removable media policy technically: block USB storage entirely, or allow only encrypted drives (BitLocker To Go required for write access) — match whatever the written MP policy says.',
        'Enable Defender scanning of removable media on access (coordinates with the Defender runbook).',
        'Document any approved exceptions (specific users/devices) with justification and expiry.',
        'Capture evidence: the media policy settings and the exception list.',
      ],
      evidenceFiles: [
        'MP.L2-3.8.7_Intune_Removable_Media_Policy_YYYY-MM-DD.png',
        'MP.L2-3.8.8_Intune_USB_Exceptions_List_YYYY-MM-DD.png',
      ],
      controls: ['MP.L2-3.8.7', 'MP.L2-3.8.8', 'MP.L2-3.8.1'],
    },
    {
      key: 'apps',
      title: 'Manage and Control Applications',
      purpose: 'Deploy what is approved; restrict what is not.',
      steps: [
        'Deploy required apps (including the enclave client such as PreVeil where used) as Required assignments so coverage is enforced, not hoped for.',
        'Document the app control stance per the written CM policy: deny-by-exception (blocklist) at minimum, allow-by-exception (AppLocker/WDAC) where feasible for CUI endpoints — record which stance applies.',
        'Restrict Microsoft Store / unapproved installs per policy for standard users.',
        'Capture evidence: required app assignments, the app control configuration.',
      ],
      evidenceFiles: [
        'CM.L2-3.4.8_Intune_App_Control_Configuration_YYYY-MM-DD.png',
        'CM.L2-3.4.9_Intune_Required_App_Assignments_YYYY-MM-DD.png',
      ],
      controls: ['CM.L2-3.4.8', 'CM.L2-3.4.9', 'AC.L2-3.1.18'],
    },
    {
      key: 'lost_device',
      title: 'Lost, Stolen, and Retired Devices',
      purpose: 'The wipe procedure is media sanitization in practice — and assessors ask to see it.',
      steps: [
        'Document the lost/stolen device procedure: report, remote lock, remote wipe (full wipe for corporate, selective/retire for BYOD), record the action.',
        'Test a remote wipe or retire on a non-production device and keep the action record as evidence.',
        'Document the device retirement flow: wipe/reset before disposal or reassignment, with a sanitization record per device (feeds MP.L2-3.8.3).',
        'Capture evidence: the procedure document, a completed wipe/retire action record.',
      ],
      evidenceFiles: [
        'MP.L2-3.8.3_Intune_Remote_Wipe_Action_Record_YYYY-MM-DD.png',
      ],
      controls: ['MP.L2-3.8.3', 'AC.L2-3.1.18', 'AC.L2-3.1.19'],
    },
    {
      key: 'gather',
      title: 'Gather Evidence',
      purpose: 'Collect the full Intune evidence package using the exact naming convention.',
      evidenceTable: [
        'Admin role assignments',
        'Enrolled device list vs asset inventory',
        'Enrollment restrictions / BYOD stance',
        'Compliance policy settings and report',
        'Conditional Access requiring compliant device',
        'Security baseline summary and deviation log',
        'Baseline assignment status',
        'BitLocker/FileVault policy',
        'Escrowed recovery key example (redacted)',
        'Encryption status report',
        'Screen lock policy',
        'Removable media policy and exceptions',
        'App control configuration and required apps',
        'Remote wipe/retire action record',
      ],
      controls: [],
    },
    {
      key: 'map',
      title: 'Map Evidence to Controls',
      purpose: 'Attach each uploaded evidence item to every control it supports.',
      steps: [
        'Upload each captured file through the Evidence module using the exact file name.',
        'Map each item to its primary control (from the file name) and additional supported controls using the mapping groups above.',
        'Intune may serve as a primary evidence source for CM.L2-3.4.1/3.4.2 (baseline + inventory), AC.L2-3.1.10 (lock), and MP.L2-3.8.7 (media) when assignment coverage is proven; most others are supporting.',
        'Do not change control status here — status changes happen in Control Implementation after validation.',
      ],
      controls: [],
    },
    {
      key: 'validate',
      title: 'Validate and Avoid Common Mistakes',
      purpose: 'Prove the policies bite, and sidestep the failures assessors see most.',
      steps: [
        'Assignment sample: pick 5 random in-scope devices and confirm each shows the compliance policy, baseline, and encryption policy applied and succeeded.',
        'Common mistake: policies created but assigned to a test group only — coverage means ALL in-scope groups.',
        'Common mistake: indefinite noncompliance grace periods, making the compliance policy decorative.',
        'Common mistake: BitLocker on but recovery keys never escrowed — one dead motherboard becomes data loss, and assessors check escrow.',
        'Common mistake: BYOD phones reading company email with no enrollment or app protection, silently expanding the boundary.',
        'When every section is complete and evidence is accepted, update the related controls in Control Implementation with reviewer validation.',
      ],
      controls: ['CA.L2-3.12.1', 'CA.L2-3.12.3'],
    },
  ],
};
