// NinjaOne CMMC Technician Runbook content. Static guidance only — no API calls.
// Each section renders as a numbered technician guide with checkboxes.

export const NINJAONE_RUNBOOK = {
  tool_name: 'NinjaOne',
  title: 'NinjaOne CMMC Technician Runbook',
  subtitle: 'Step-by-step setup, policy configuration, evidence collection, and control mapping guide.',
  intro:
    'This runbook guides technicians through preparing NinjaOne to support CMMC Level 2 readiness. NinjaOne may provide supporting evidence for selected controls related to endpoint inventory, patching, vulnerability visibility, remote management, administrative access, and remediation tracking. NinjaOne does not satisfy CMMC requirements by itself. All evidence must be validated by authorized personnel.',
  evidenceNaming: {
    format: 'CONTROLID_ToolName_EvidenceDescription_YYYY-MM-DD.png',
    toolName: 'NinjaOne',
    examples: [
      'SI.L2-3.14.1_NinjaOne_OS_Patch_Policy_2026-07-05.png',
      'SI.L2-3.14.2_NinjaOne_Missing_Patches_Report_2026-07-05.png',
      'RA.L2-3.11.2_NinjaOne_Vulnerability_Dashboard_2026-07-05.png',
      'AC.L2-3.1.2_NinjaOne_Admin_User_List_2026-07-05.png',
      'MA.L2-3.7.5_NinjaOne_Remote_Access_Settings_2026-07-05.png',
    ],
    rules: [
      'Start every file name with the primary CMMC control ID.',
      'Use NinjaOne as the tool name.',
      'Use short descriptive names.',
      'Use underscores instead of spaces.',
      'Use YYYY-MM-DD date format.',
      'Do not use vague names like screenshot1.png, evidence.png, or ninja.png.',
      'If one screenshot supports multiple controls, name it after the primary control and map it to additional controls inside Kipuka.',
      'If the screenshot includes sensitive information, sanitize it before upload or mark it sensitive according to project rules.',
    ],
  },
  // Suggested mappings (for the Map Evidence section).
  mappingGroups: [
    { label: 'Endpoint inventory evidence may support', controls: ['CM.L2-3.4.1', 'CM.L2-3.4.2', 'CA.L2-3.12.1', 'CA.L2-3.12.3'] },
    { label: 'Patch management evidence may support', controls: ['SI.L2-3.14.1', 'SI.L2-3.14.2', 'SI.L2-3.14.4', 'RA.L2-3.11.2', 'RA.L2-3.11.3', 'CM.L2-3.4.2'] },
    { label: 'Third-party patching evidence may support', controls: ['SI.L2-3.14.1', 'SI.L2-3.14.2', 'SI.L2-3.14.4', 'RA.L2-3.11.2', 'RA.L2-3.11.3'] },
    { label: 'Vulnerability visibility evidence may support', controls: ['RA.L2-3.11.2', 'RA.L2-3.11.3', 'SI.L2-3.14.2', 'SI.L2-3.14.4', 'CA.L2-3.12.2'] },
    { label: 'Admin access evidence may support', controls: ['AC.L2-3.1.1', 'AC.L2-3.1.2', 'AC.L2-3.1.5', 'AC.L2-3.1.6', 'IA.L2-3.5.3', 'IA.L2-3.5.5'] },
    { label: 'Remote access evidence may support', controls: ['MA.L2-3.7.5', 'MA.L2-3.7.6', 'AC.L2-3.1.12', 'AC.L2-3.1.13'] },
    { label: 'Alert/monitoring evidence may support', controls: ['SI.L2-3.14.6', 'SI.L2-3.14.7', 'CA.L2-3.12.3', 'CM.L2-3.4.7'] },
  ],
  finalWarning:
    'Do not mark controls as implemented based only on NinjaOne evidence. NinjaOne evidence is supporting evidence. Final control status must consider policy, process, configuration, interviews, implementation, and reviewer validation.',
  sections: [
    {
      key: 'overview',
      title: 'Technician Checklist Overview',
      purpose: 'Track overall progress through the NinjaOne readiness workflow at a glance.',
      checklist: [
        'NinjaOne organization created or verified',
        'Client sites/locations configured',
        'In-scope devices enrolled',
        'Out-of-scope devices documented',
        'Device groups/tags configured',
        'OS patch policy created or copied',
        'Third-party patch policy created or copied, if licensed',
        'Vulnerability visibility reviewed, if licensed',
        'Remote access settings reviewed',
        'NinjaOne admin access reviewed',
        'Alerts/monitoring configured',
        'Evidence screenshots captured',
        'Reports exported',
        'Evidence files named correctly',
        'Evidence uploaded',
        'Evidence mapped to controls',
        'Gaps converted to POA&M or ACOLYTE remediation items',
        'Technician review complete',
      ],
    },
    {
      key: 'organization',
      title: 'Create or Verify NinjaOne Organization',
      purpose: 'Ensure a correct, isolated NinjaOne organization scoped to this client exists.',
      steps: [
        'Log in to NinjaOne using an authorized Pac-Sec or client administrator account.',
        'Go to the organization/customer management area.',
        'Create a new organization for the client or verify the existing organization.',
        'Use the client\u2019s legal or approved short name as the organization name.',
        'Create or verify sites/locations that match the client\u2019s CMMC project scope.',
        'Verify the organization does not contain devices from another customer.',
        'Document any devices that are out of scope.',
        'Capture evidence screenshots.',
      ],
      evidenceFiles: [
        'CM.L2-3.4.1_NinjaOne_Organization_Overview_YYYY-MM-DD.png',
        'CM.L2-3.4.1_NinjaOne_Site_Structure_YYYY-MM-DD.png',
        'CM.L2-3.4.1_NinjaOne_Managed_Device_Count_YYYY-MM-DD.png',
      ],
      controls: ['CM.L2-3.4.1', 'CM.L2-3.4.2', 'CA.L2-3.12.1', 'RA.L2-3.11.1'],
    },
    {
      key: 'baseline_policies',
      title: 'Create or Copy Baseline Policies',
      purpose: 'Apply consistent, reviewed baseline policies to in-scope devices only.',
      steps: [
        'Go to NinjaOne policy management.',
        'Check whether a Pac-Sec baseline policy template already exists.',
        'If a template exists, copy the template into the client organization.',
        'Rename the copied policy using this format: CLIENTNAME - CMMC Baseline - POLICYTYPE',
        'Example: Acme Defense - CMMC Baseline - Windows Patch Policy',
        'If no template exists, create a new policy manually using the required configuration checklist.',
        'Assign policies only to in-scope device groups after technician review.',
        'Do not apply policies blindly to out-of-scope devices.',
      ],
      lists: [
        {
          label: 'Recommended baseline NinjaOne policies',
          items: [
            'CMMC Baseline - Windows OS Patch Policy',
            'CMMC Baseline - Third-Party Patch Policy',
            'CMMC Baseline - Endpoint Monitoring Policy',
            'CMMC Baseline - Server Patch Policy, if servers are in scope',
            'CMMC Baseline - Workstation Patch Policy',
            'CMMC Baseline - macOS Patch Policy, if macOS endpoints are in scope',
            'CMMC Baseline - Remote Access Review Policy or configuration record',
            'CMMC Baseline - Vulnerability Review Procedure, if licensed',
          ],
        },
      ],
      evidenceFiles: [
        'CM.L2-3.4.2_NinjaOne_Baseline_Policy_List_YYYY-MM-DD.png',
        'SI.L2-3.14.1_NinjaOne_OS_Patch_Policy_YYYY-MM-DD.png',
        'SI.L2-3.14.1_NinjaOne_Third_Party_Patch_Policy_YYYY-MM-DD.png',
        'CM.L2-3.4.7_NinjaOne_Endpoint_Monitoring_Policy_YYYY-MM-DD.png',
      ],
      controls: ['CM.L2-3.4.1', 'CM.L2-3.4.2', 'CM.L2-3.4.6', 'CM.L2-3.4.7', 'SI.L2-3.14.1', 'SI.L2-3.14.2', 'SI.L2-3.14.4'],
    },
    {
      key: 'inventory',
      title: 'Configure Endpoint Inventory and Device Groups',
      purpose: 'Confirm every in-scope endpoint is enrolled and correctly grouped.',
      steps: [
        'Review all devices in the NinjaOne organization.',
        'Confirm every in-scope endpoint is enrolled.',
        'Confirm each device has hostname, operating system, device type, last check-in date, assigned user or owner if available, site/location, and device group or tag.',
        'Create groups or tags for: CMMC In Scope, CMMC Out of Scope, CUI Users, Servers, Workstations, macOS Devices, Windows Devices, High Priority Systems.',
        'Export or screenshot endpoint inventory.',
        'Upload the evidence to Kipuka.',
      ],
      evidenceFiles: [
        'CM.L2-3.4.1_NinjaOne_Endpoint_Inventory_YYYY-MM-DD.png',
        'CM.L2-3.4.1_NinjaOne_InScope_Device_Group_YYYY-MM-DD.png',
        'CM.L2-3.4.1_NinjaOne_Device_Last_CheckIn_YYYY-MM-DD.png',
        'CA.L2-3.12.1_NinjaOne_CMMC_Scope_Device_List_YYYY-MM-DD.png',
      ],
      controls: ['CM.L2-3.4.1', 'CM.L2-3.4.2', 'CA.L2-3.12.1', 'CA.L2-3.12.3', 'RA.L2-3.11.1'],
    },
    {
      key: 'patch',
      title: 'Configure Patch Management',
      purpose: 'Ensure OS patching is enabled, scheduled, and reported for in-scope endpoints.',
      steps: [
        'Open the client\u2019s NinjaOne patch management policy.',
        'Confirm operating system patching is enabled for in-scope endpoints.',
        'Configure patch schedule according to client-approved maintenance windows.',
        'Configure approval behavior according to Pac-Sec/client policy.',
        'Configure reboot behavior.',
        'Configure handling for failed patches and offline devices.',
        'Review missing patch report.',
        'Capture screenshots of patch policy, patch schedule, reboot settings, patch approval settings, patch compliance dashboard/report, and missing patch report.',
      ],
      evidenceFiles: [
        'SI.L2-3.14.1_NinjaOne_OS_Patch_Policy_YYYY-MM-DD.png',
        'SI.L2-3.14.1_NinjaOne_Patch_Schedule_YYYY-MM-DD.png',
        'SI.L2-3.14.1_NinjaOne_Reboot_Settings_YYYY-MM-DD.png',
        'SI.L2-3.14.1_NinjaOne_Patch_Compliance_Report_YYYY-MM-DD.png',
        'SI.L2-3.14.2_NinjaOne_Missing_Patches_Report_YYYY-MM-DD.png',
        'SI.L2-3.14.2_NinjaOne_Failed_Patches_Report_YYYY-MM-DD.png',
      ],
      controls: ['SI.L2-3.14.1', 'SI.L2-3.14.2', 'SI.L2-3.14.4', 'RA.L2-3.11.2', 'RA.L2-3.11.3', 'CM.L2-3.4.2'],
    },
    {
      key: 'third_party_patch',
      title: 'Configure Third-Party Patching, if licensed',
      purpose: 'Extend patching to third-party applications where licensed.',
      conditional: 'Only if third-party patching is licensed and enabled.',
      steps: [
        'Confirm whether third-party patching is licensed and enabled.',
        'Identify which third-party applications are supported.',
        'Configure third-party application patch policy.',
        'Review missing third-party application updates.',
        'Capture screenshots or exports for third-party patch policy, supported application list, third-party patch compliance, and missing third-party patches.',
      ],
      evidenceFiles: [
        'SI.L2-3.14.1_NinjaOne_Third_Party_Patch_Policy_YYYY-MM-DD.png',
        'SI.L2-3.14.1_NinjaOne_Third_Party_App_List_YYYY-MM-DD.png',
        'SI.L2-3.14.2_NinjaOne_Third_Party_Patch_Compliance_YYYY-MM-DD.png',
        'RA.L2-3.11.3_NinjaOne_Third_Party_Missing_Patches_YYYY-MM-DD.png',
      ],
      controls: ['SI.L2-3.14.1', 'SI.L2-3.14.2', 'SI.L2-3.14.4', 'RA.L2-3.11.2', 'RA.L2-3.11.3'],
    },
    {
      key: 'vulnerability',
      title: 'Configure Vulnerability Visibility, if licensed',
      purpose: 'Review and track vulnerability findings where licensed.',
      conditional: 'Only if NinjaOne vulnerability visibility/reporting is licensed and enabled.',
      steps: [
        'Confirm whether NinjaOne vulnerability visibility or reporting is licensed and enabled.',
        'Open the vulnerability dashboard or report area.',
        'Review critical and high findings.',
        'Document the remediation approach.',
        'Create POA&M or ACOLYTE remediation items for unresolved high-risk findings.',
        'Capture screenshots or exports for vulnerability dashboard, critical/high vulnerability summary, remediation status, and device vulnerability detail.',
      ],
      evidenceFiles: [
        'RA.L2-3.11.2_NinjaOne_Vulnerability_Dashboard_YYYY-MM-DD.png',
        'RA.L2-3.11.2_NinjaOne_Critical_High_Findings_YYYY-MM-DD.png',
        'RA.L2-3.11.3_NinjaOne_Vulnerability_Remediation_Status_YYYY-MM-DD.png',
        'SI.L2-3.14.2_NinjaOne_Flaw_Remediation_Tracking_YYYY-MM-DD.png',
      ],
      controls: ['RA.L2-3.11.2', 'RA.L2-3.11.3', 'SI.L2-3.14.2', 'SI.L2-3.14.4', 'CA.L2-3.12.2'],
    },
    {
      key: 'remote_access',
      title: 'Configure Remote Access and Admin Permissions',
      purpose: 'Confirm least-privilege administrative and remote access to NinjaOne.',
      steps: [
        'Review NinjaOne administrator accounts.',
        'Confirm only authorized personnel have administrative access.',
        'Confirm technician roles are assigned based on least privilege.',
        'Confirm MFA is enabled for NinjaOne administrators where available.',
        'Review remote access settings.',
        'Document who may initiate remote sessions.',
        'Capture screenshots of NinjaOne user/admin list, role assignments, MFA or SSO settings if visible, remote access settings, and remote session permission settings.',
      ],
      evidenceFiles: [
        'AC.L2-3.1.2_NinjaOne_Admin_User_List_YYYY-MM-DD.png',
        'AC.L2-3.1.5_NinjaOne_Role_Assignments_YYYY-MM-DD.png',
        'IA.L2-3.5.3_NinjaOne_Admin_MFA_Settings_YYYY-MM-DD.png',
        'MA.L2-3.7.5_NinjaOne_Remote_Access_Settings_YYYY-MM-DD.png',
        'MA.L2-3.7.6_NinjaOne_Remote_Session_Permissions_YYYY-MM-DD.png',
      ],
      controls: ['AC.L2-3.1.1', 'AC.L2-3.1.2', 'AC.L2-3.1.5', 'AC.L2-3.1.6', 'IA.L2-3.5.3', 'IA.L2-3.5.5', 'MA.L2-3.7.5', 'MA.L2-3.7.6'],
    },
    {
      key: 'alerts',
      title: 'Configure Alerts and Monitoring',
      purpose: 'Enable alerting so device health and patch failures are visible.',
      steps: [
        'Review available NinjaOne alert policies.',
        'Configure alerts for offline devices, patch failures, critical device health issues, low disk space if applicable, security tool status if monitored, and reboot required if applicable.',
        'Confirm who receives or reviews alerts.',
        'Capture screenshots for alert policy list, patch failure alert, offline device alert, device health alert, and alert routing or notification settings.',
      ],
      evidenceFiles: [
        'SI.L2-3.14.6_NinjaOne_Alert_Policy_List_YYYY-MM-DD.png',
        'SI.L2-3.14.6_NinjaOne_Patch_Failure_Alert_YYYY-MM-DD.png',
        'SI.L2-3.14.7_NinjaOne_Offline_Device_Alert_YYYY-MM-DD.png',
        'CA.L2-3.12.3_NinjaOne_Device_Health_Alert_YYYY-MM-DD.png',
      ],
      controls: ['SI.L2-3.14.6', 'SI.L2-3.14.7', 'CA.L2-3.12.3', 'CM.L2-3.4.7'],
    },
    {
      key: 'gather_evidence',
      title: 'Gather Evidence Screenshots and Reports',
      purpose: 'Assemble the full NinjaOne evidence package.',
      evidenceTable: [
        'NinjaOne organization overview',
        'Site/location structure',
        'Endpoint inventory',
        'CMMC in-scope device group/tag',
        'Patch policy',
        'Patch compliance report',
        'Missing patch report',
        'Third-party patch policy, if licensed',
        'Third-party patch compliance, if licensed',
        'Vulnerability dashboard, if licensed',
        'Critical/high vulnerability summary, if licensed',
        'NinjaOne admin user list',
        'NinjaOne role assignments',
        'MFA/SSO admin settings, if available',
        'Remote access settings, if used',
        'Alert policy list',
        'Patch failure alert policy',
        'Device health alert policy',
        'Remediation tracking evidence',
        'Exception list, if applicable',
      ],
    },
    {
      key: 'naming',
      title: 'Evidence Naming Standard',
      purpose: 'Name every file consistently so evidence maps cleanly to controls.',
      isNaming: true,
    },
    {
      key: 'upload',
      title: 'Upload Evidence to Kipuka',
      purpose: 'Log each named artifact in the Evidence Vault and map it to controls.',
      isUpload: true,
      steps: [
        'Open the client project in Kipuka.',
        'Go to Evidence Vault.',
        'Click Upload Evidence.',
        'Select source tool: NinjaOne.',
        'Upload the properly named screenshot or report.',
        'Set evidence type: Screenshot, Report Export, Configuration Export, Dashboard View, or Other.',
        'Enter evidence date.',
        'Add owner.',
        'Add description explaining what the evidence shows.',
        'Map the evidence to the applicable controls.',
        'Set review status to Needs Review.',
        'Save the evidence record.',
        'Verify it appears under the mapped controls.',
      ],
    },
    {
      key: 'mapping',
      title: 'Map Evidence to CMMC Controls',
      purpose: 'Map NinjaOne evidence only to controls it actually supports.',
      isMapping: true,
      importantNote:
        'NinjaOne evidence should be mapped only to controls it actually supports. Do not map NinjaOne evidence to every CMMC control.',
    },
    {
      key: 'gaps',
      title: 'Create POA&M or ACOLYTE Remediation Items for Gaps',
      purpose: 'Convert unresolved gaps into tracked remediation work — manually.',
      isGaps: true,
      steps: [
        'Review missing evidence and failed configuration items.',
        'For each unresolved issue, decide whether it requires: POA&M item, ACOLYTE remediation item, Both, or Technician note only.',
        'Create a POA&M item for compliance-impacting gaps.',
        'Create an ACOLYTE remediation item for operational cyber readiness gaps if ACOLYTE is enabled.',
        'Link the gap to the related evidence and controls.',
      ],
      lists: [
        {
          label: 'Example gaps',
          items: [
            'Missing patch policy evidence',
            'Critical patches outstanding',
            'Vulnerability report shows unresolved critical findings',
            'NinjaOne admin MFA not confirmed',
            'Remote access permission model not documented',
            'In-scope devices missing from NinjaOne',
          ],
        },
      ],
    },
    {
      key: 'final_review',
      title: 'Final Technician Review',
      purpose: 'Confirm the NinjaOne evidence package is complete and reviewer-ready.',
      isFinal: true,
      checklist: [
        'NinjaOne organization is correct.',
        'Client sites/locations are correct.',
        'Only client devices are present.',
        'In-scope devices are tagged/grouped.',
        'Out-of-scope devices are documented.',
        'Baseline policies are copied or created.',
        'Patch policy evidence captured.',
        'Patch compliance evidence captured.',
        'Third-party patch evidence captured, if applicable.',
        'Vulnerability evidence captured, if applicable.',
        'Admin access evidence captured.',
        'Remote access evidence captured, if applicable.',
        'Alert policy evidence captured.',
        'All screenshots are named using the required naming standard.',
        'Evidence is uploaded to Kipuka.',
        'Evidence is mapped only to applicable controls.',
        'Gaps are converted to POA&M or ACOLYTE remediation items.',
        'Technician notes are complete.',
        'Evidence review status is set to Needs Review.',
        'Pac-Sec or client reviewer is assigned.',
      ],
    },
  ],
};