// PreVeil CMMC Technician Runbook content. Static guidance only — no API calls.
// PreVeil is an end-to-end encrypted email + file sharing enclave that overlays
// an EXISTING Microsoft 365 Commercial (or Google Workspace) environment so CUI
// never touches the non-compliant commercial platform. CUI is stored encrypted
// on AWS GovCloud (FedRAMP High infrastructure); PreVeil holds DoD FedRAMP
// Moderate equivalency, uses FIPS 140-2 validated encryption modules, and
// supports DFARS 252.204-7012 (c)-(g) incident reporting obligations.
// This is typically the LOWEST-COST compliant CUI path for small contractors:
// license only CUI-touching users and keep everyone else on commercial M365,
// instead of an enterprise-wide GCC High migration.

export const PREVEIL_RUNBOOK = {
  tool_name: 'PreVeil',
  title: 'PreVeil CMMC Technician Runbook',
  subtitle: 'CUI enclave setup: provisioning, deployment, admin hardening, CUI migration, evidence collection, and control mapping.',
  intro:
    'This runbook guides technicians through deploying PreVeil as the CUI enclave for a contractor whose base environment is Microsoft 365 Commercial (which is NOT compliant for storing, processing, or transmitting CUI under DFARS 252.204-7012). After this runbook, all CUI email and files live inside PreVeil (end-to-end encrypted, stored on AWS GovCloud), the commercial tenant is documented as out-of-scope for CUI, and the assessment boundary reflects the enclave. PreVeil supports many NIST 800-171 controls but does not satisfy any control by itself — policy, process, and validation are still required.',
  evidenceNaming: {
    format: 'CONTROLID_ToolName_EvidenceDescription_YYYY-MM-DD.png',
    toolName: 'PreVeil',
    examples: [
      'SC.L2-3.13.11_PreVeil_FIPS_Encryption_Statement_2026-07-10.png',
      'AC.L2-3.1.3_PreVeil_TrustedCommunity_Settings_2026-07-10.png',
      'SC.L2-3.13.16_PreVeil_Drive_CUI_Folder_Structure_2026-07-10.png',
      'AC.L2-3.1.5_PreVeil_ApprovalGroup_Admin_Actions_2026-07-10.png',
      'IR.L2-3.6.1_PreVeil_Incident_Support_Contact_2026-07-10.png',
    ],
    rules: [
      'Start every file name with the primary CMMC control ID.',
      'Use PreVeil as the tool name.',
      'Use short descriptive names with underscores instead of spaces.',
      'Use YYYY-MM-DD date format.',
      'Do not use vague names like screenshot1.png or preveil.png.',
      'If one screenshot supports multiple controls, name it after the primary control and map it to additional controls on the current control's Evidence page.',
      'Never capture actual CUI content in evidence screenshots — show settings, folder structures, and policies, not controlled data.',
    ],
  },
  mappingGroups: [
    { label: 'Encryption evidence may support', controls: ['SC.L2-3.13.8', 'SC.L2-3.13.11', 'SC.L2-3.13.16', 'AC.L2-3.1.19'] },
    { label: 'CUI flow restriction evidence may support', controls: ['AC.L2-3.1.3', 'AC.L2-3.1.20', 'AC.L2-3.1.22', 'SC.L2-3.13.1'] },
    { label: 'Admin approval group evidence may support', controls: ['AC.L2-3.1.5', 'AC.L2-3.1.6', 'AC.L2-3.1.7', 'IA.L2-3.5.3'] },
    { label: 'Device and access evidence may support', controls: ['AC.L2-3.1.1', 'AC.L2-3.1.12', 'AC.L2-3.1.13', 'IA.L2-3.5.1', 'IA.L2-3.5.2'] },
    { label: 'Activity log evidence may support', controls: ['AU.L2-3.3.1', 'AU.L2-3.3.2', 'AU.L2-3.3.5'] },
    { label: 'Incident reporting support evidence may support', controls: ['IR.L2-3.6.1', 'IR.L2-3.6.2'] },
    { label: 'Backup/availability evidence may support', controls: ['MP.L2-3.8.9', 'CP-related project procedures'] },
  ],
  finalWarning:
    'Do not mark controls as implemented based only on PreVeil evidence. The enclave protects CUI in email and files only — endpoints, physical security, personnel, training, and the processes around the enclave still require their own implementation and evidence. Calendar and contacts remain on the base system: ensure no CUI is placed in meeting invites or contact records, and document that rule in policy.',
  sections: [
    {
      key: 'overview',
      title: 'Technician Checklist Overview',
      purpose: 'Track overall progress through the PreVeil CUI enclave deployment at a glance.',
      checklist: [
        'CUI users, data, and flows identified and documented',
        'Enclave boundary defined in the Scoping module and diagrams',
        'PreVeil organization provisioned and domain configured',
        'PreVeil deployed to every CUI-touching user (desktop + mobile)',
        'Approval groups configured for privileged admin actions',
        'Recovery group configured and tested',
        'Trusted Communities configured to restrict CUI flow',
        'Device list reviewed; lost-device lock procedure documented',
        'CUI email and files migrated into PreVeil',
        'CUI purged from commercial M365 (OneDrive/SharePoint/Exchange)',
        'Subcontractor/partner Express accounts established where needed',
        'SRM updated with PreVeil as provider; PreVeil compliance docs obtained',
        'SSP data flows and IR plan updated for the enclave',
        'Evidence screenshots captured with correct names',
        'Evidence mapped to the required controls',
      ],
    },
    {
      key: 'scoping',
      title: 'Define the CUI Enclave Boundary',
      purpose: 'Decide exactly which people, data, and flows enter the enclave — the assessor evaluates the system that holds CUI.',
      steps: [
        'List every user who receives, creates, or sends CUI (engineering, contracts, quality, leadership as applicable). Only these users need PreVeil licenses.',
        'List every current location of CUI: mailboxes, OneDrive/SharePoint folders, file servers, removable media.',
        'Document each external party that exchanges CUI with the organization (primes, DoD, subcontractors).',
        'In the project's Preliminary Scope module, record the enclave approach: PreVeil = CUI Asset boundary; commercial M365 = out-of-scope for CUI (FCI and general business only).',
        'Update the Network Diagram and CUI Data Flow Diagram: CUI flows only between PreVeil clients and AWS GovCloud storage; no CUI path may touch commercial Exchange/OneDrive/SharePoint.',
        'Write down the calendar/contacts rule: PreVeil does not cover calendar or contacts, so no CUI may ever be placed in meeting invites, calendar bodies, or contact notes. This becomes a policy statement and a training point.',
        'Capture evidence screenshots of the updated scoping record and diagrams.',
      ],
      evidenceFiles: [
        'AC.L2-3.1.3_PreVeil_CUI_DataFlow_Diagram_YYYY-MM-DD.png',
        'CA.L2-3.12.4_PreVeil_Enclave_Scope_Statement_YYYY-MM-DD.png',
      ],
      controls: ['AC.L2-3.1.3', 'CA.L2-3.12.4', 'SC.L2-3.13.1'],
    },
    {
      key: 'provision',
      title: 'Provision the PreVeil Organization',
      purpose: 'Stand up the PreVeil org correctly before any user deployment.',
      steps: [
        'Purchase PreVeil directly (no migration partner is required) — choose the CMMC/compliance bundle; confirm it includes the compliance documentation package (pre-filled SSP/policy content and the PreVeil shared responsibility matrix).',
        'Create the PreVeil organization with an authorized administrator account.',
        'Add and verify the organization\u2019s email domain so users keep their EXISTING email addresses inside PreVeil.',
        'Record in writing: CUI at rest is stored end-to-end encrypted on AWS GovCloud (FedRAMP High infrastructure); PreVeil holds DoD FedRAMP Moderate equivalency and uses FIPS 140-2 validated cryptographic modules. Request PreVeil\u2019s current equivalency/body-of-evidence letter for the assessor.',
        'Confirm DFARS 252.204-7012 (c)-(g) incident reporting support is included and note PreVeil\u2019s incident support contact for the IR plan.',
        'Capture evidence screenshots of the org settings and domain verification.',
      ],
      evidenceFiles: [
        'SC.L2-3.13.11_PreVeil_FIPS_Encryption_Statement_YYYY-MM-DD.png',
        'SC.L2-3.13.16_PreVeil_Org_Settings_YYYY-MM-DD.png',
      ],
      controls: ['SC.L2-3.13.11', 'SC.L2-3.13.16', 'SC.L2-3.13.8'],
    },
    {
      key: 'deploy',
      title: 'Deploy PreVeil to CUI Users',
      purpose: 'Install and verify the enclave client for every CUI-touching user on every device they use for CUI.',
      steps: [
        'Install the PreVeil desktop application on each CUI user\u2019s Windows PC or Mac.',
        'Verify the Outlook integration (or Gmail/Apple Mail as applicable) shows the PreVeil encrypted mailbox alongside the normal mailbox, using the user\u2019s existing email address.',
        'Verify PreVeil Drive appears in Windows Explorer / Mac Finder for encrypted file storage and sharing.',
        'Install the PreVeil mobile app (iOS/Android) only for users approved to access CUI on mobile devices; document which users have mobile access.',
        'Confirm each user\u2019s account uses PreVeil device-based cryptographic authentication (no passwords to phish) and record the enrolled devices per user.',
        'Have each user send a test encrypted message and store a test file in PreVeil Drive; verify end-to-end encryption indicators.',
        'Capture evidence screenshots (client installed, integration active, device list).',
      ],
      evidenceFiles: [
        'AC.L2-3.1.1_PreVeil_User_Device_List_YYYY-MM-DD.png',
        'IA.L2-3.5.2_PreVeil_Device_Authentication_YYYY-MM-DD.png',
      ],
      controls: ['AC.L2-3.1.1', 'IA.L2-3.5.1', 'IA.L2-3.5.2', 'AC.L2-3.1.19'],
    },
    {
      key: 'admin_controls',
      title: 'Harden the Admin Console',
      purpose: 'Configure PreVeil\u2019s cryptographic admin protections so no single administrator can compromise the enclave.',
      steps: [
        'Create an Approval Group for privileged actions (data export, user deletion, recovery): require multiple named approvers (e.g., 2 of 3) so no lone admin can exfiltrate or destroy CUI.',
        'Configure the Recovery Group for account recovery and test the recovery flow with a non-production account.',
        'Review the organization device list; document and test the procedure to lock/wipe a lost or stolen device\u2019s PreVeil access.',
        'Configure Trusted Communities: restrict who can exchange CUI with your users — limit to verified primes, DoD addresses, and approved subcontractors. This is your technical enforcement of CUI flow control.',
        'Review admin activity logging in the Admin Console and document where logs are reviewed and by whom (feeds the AU family evidence).',
        'Document the admin roster: who holds PreVeil admin, who sits in approval/recovery groups, and the review cadence for that roster.',
        'Capture evidence screenshots of each configured protection.',
      ],
      evidenceFiles: [
        'AC.L2-3.1.5_PreVeil_ApprovalGroup_Admin_Actions_YYYY-MM-DD.png',
        'AC.L2-3.1.3_PreVeil_TrustedCommunity_Settings_YYYY-MM-DD.png',
        'AU.L2-3.3.1_PreVeil_Admin_Activity_Log_YYYY-MM-DD.png',
      ],
      controls: ['AC.L2-3.1.3', 'AC.L2-3.1.5', 'AC.L2-3.1.6', 'AC.L2-3.1.7', 'AU.L2-3.3.1', 'AU.L2-3.3.2'],
    },
    {
      key: 'migrate',
      title: 'Migrate CUI Into the Enclave',
      purpose: 'Move all CUI into PreVeil and eliminate it from the non-compliant commercial environment.',
      steps: [
        'Using the CUI inventory from the scoping section, move CUI files from OneDrive/SharePoint/file shares into PreVeil Drive, preserving a documented folder structure (e.g., by contract).',
        'For CUI held in email, forward/import required CUI messages into the PreVeil mailbox, then delete them from the commercial mailbox (including Sent and Deleted Items).',
        'Purge residual CUI from the commercial tenant: search OneDrive, SharePoint, Teams, and Exchange for known CUI file names/markings; delete and empty recycle bins/retention as policy allows. Document the purge date and method.',
        'Establish free PreVeil Express accounts for subcontractors and partners who must exchange CUI, and add them to Trusted Communities. Notify primes of your new CUI exchange address/process.',
        'Issue the user rule in writing: from the cutover date, CUI may ONLY be created, stored, or sent inside PreVeil. Include the calendar/contacts prohibition.',
        'Capture evidence: PreVeil Drive structure, purge documentation, partner community list.',
      ],
      evidenceFiles: [
        'SC.L2-3.13.16_PreVeil_Drive_CUI_Folder_Structure_YYYY-MM-DD.png',
        'AC.L2-3.1.20_PreVeil_Partner_Express_Accounts_YYYY-MM-DD.png',
        'MP.L2-3.8.3_Commercial_Tenant_CUI_Purge_Record_YYYY-MM-DD.png',
      ],
      controls: ['SC.L2-3.13.16', 'AC.L2-3.1.20', 'AC.L2-3.1.3', 'MP.L2-3.8.3'],
    },
    {
      key: 'policies',
      title: 'Update SSP, SRM, and IR Plan',
      purpose: 'Make the documentation match the new enclave reality — the number one thing assessors check.',
      steps: [
        'In the project's Shared Responsibility module, add PreVeil as an External Service Provider and load its shared responsibility matrix (request the current CMMC SRM from PreVeil\u2019s compliance package); mark inherited vs customer responsibilities per control.',
        'Update the SSP system description and data flows: CUI system = PreVeil enclave (+ endpoints and people that touch it); commercial M365 = out of scope for CUI.',
        'Update the Incident Response Plan: PreVeil supports DFARS 7012 (c)-(g); add PreVeil\u2019s incident contact and the flow for the 72-hour DIBNet report, malware submission to DC3, and 90-day preservation.',
        'Update the media protection / acceptable use policies with the PreVeil-only CUI rule and the calendar/contacts prohibition.',
        'Deliver a short user training on the new CUI workflow and record attendance (AT family evidence).',
        'Capture evidence of updated documents and training records.',
      ],
      evidenceFiles: [
        'IR.L2-3.6.1_PreVeil_IR_Plan_Update_YYYY-MM-DD.png',
        'AT.L2-3.2.1_PreVeil_CUI_Workflow_Training_Record_YYYY-MM-DD.png',
      ],
      controls: ['IR.L2-3.6.1', 'IR.L2-3.6.2', 'AT.L2-3.2.1', 'CA.L2-3.12.4'],
    },
    {
      key: 'gather',
      title: 'Gather Evidence',
      purpose: 'Collect the full PreVeil evidence package using the exact naming convention.',
      evidenceTable: [
        'PreVeil org settings and verified domain',
        'FIPS 140-2 / FedRAMP Moderate equivalency statement',
        'User and device list',
        'Approval Group configuration',
        'Recovery Group configuration',
        'Trusted Communities configuration',
        'PreVeil Drive CUI folder structure',
        'Partner/subcontractor Express account list',
        'Commercial tenant CUI purge record',
        'Admin activity log sample',
        'Updated CUI data flow diagram',
        'IR plan section showing PreVeil incident support',
        'User training record for the CUI workflow',
      ],
      controls: [],
    },
    {
      key: 'map',
      title: 'Map Evidence to Controls',
      purpose: 'Attach each uploaded evidence item to every control it supports.',
      steps: [
        'Upload each captured file through the Evidence module using the exact file name.',
        'Map each item to its primary control (from the file name) and any additional supported controls using the mapping groups above.',
        'Mark PreVeil-derived items as Supporting or Primary evidence per the control: encryption controls (3.13.8, 3.13.11, 3.13.16) may treat PreVeil as a primary source; most others are supporting.',
        'Do not change any control status here — status changes happen in Control Implementation after validation.',
      ],
      controls: [],
    },
    {
      key: 'validate',
      title: 'Validate and Avoid Common Mistakes',
      purpose: 'Confirm the enclave actually holds, and sidestep the failures assessors see most.',
      steps: [
        'Test: send a CUI-marked test document through PreVeil to an approved partner and confirm delivery encrypted; attempt to send to a non-trusted address and confirm the community restriction behaves as configured.',
        'Verify no CUI remains in the commercial tenant (spot-search OneDrive/SharePoint/Exchange).',
        'Common mistake: claiming the whole company is compliant because PreVeil exists — only the enclave and its users are in the CUI boundary; everything else needs FCI-level hygiene and clear documentation.',
        'Common mistake: CUI leaking into calendar invites, Teams chats, or contact notes — those are OUTSIDE PreVeil. Train it, police it, write it down.',
        'Common mistake: no equivalency documentation on hand — assessors will ask for PreVeil\u2019s FedRAMP Moderate equivalency evidence; keep the current letter in the evidence vault.',
        'Common mistake: single-admin control of the enclave with no approval group — configure it before assessment, not after a finding.',
        'When every section is complete and evidence is accepted, update the related controls in Control Implementation with reviewer validation.',
      ],
      controls: ['CA.L2-3.12.1', 'CA.L2-3.12.3'],
    },
  ],
};
